version = 2
device = "flkey-mini-pads"
name = "Default"
active-color = 26

[pads.1]
color = 54
note = "C4"

[pads.2]
color = 38
note = "D4"

[pads.3]
color = 38
note = "Eb4"

[pads.4]
color = 38
note = "F4"

[pads.5]
color = 38
note = "G4"

[pads.6]
color = 38
note = "Ab4"

[pads.7]
color = 38
note = "Bb4"

[pads.8]
color = 54
note = "C5"

[pads.9]
color = 54
note = "C3"

[pads.10]
color = 38
note = "D3"

[pads.11]
color = 38
note = "Eb3"

[pads.12]
color = 38
note = "F3"

[pads.13]
color = 38
note = "G3"

[pads.14]
color = 38
note = "Ab3"

[pads.15]
color = 38
note = "Bb3"

[pads.16]
color = 54
note = "C4"
