version = 2
device = "launchkey-mk3-faders"
name = "Default"
active-color = 26

[faders.1]
cc = 71

[faders.2]
cc = 72

[faders.3]
cc = 73

[faders.4]
cc = 74

[faders.5]
cc = 75

[faders.6]
cc = 76

[faders.7]
cc = 77

[faders.8]
cc = 78

[faders.9]
cc = 79

[buttons.1]
color = 36
cc = 11

[buttons.2]
color = 36
cc = 12

[buttons.3]
color = 36
cc = 13

[buttons.4]
color = 36
cc = 14

[buttons.5]
color = 36
cc = 15

[buttons.6]
color = 36
cc = 16

[buttons.7]
color = 36
cc = 17

[buttons.8]
color = 36
cc = 18

[buttons.9]
cc = 19
