version = 2
device = "launchkey-mini-mk3-pads"
name = "Colors 0-15"
active-color = 0

[pads.1]
color = 0
note = 0

[pads.2]
color = 1
note = 1

[pads.3]
color = 2
note = 2

[pads.4]
color = 3
note = 3

[pads.5]
color = 4
note = 4

[pads.6]
color = 5
note = 5

[pads.7]
color = 6
note = 6

[pads.8]
color = 7
note = 7

[pads.9]
color = 8
note = 8

[pads.10]
color = 9
note = 9

[pads.11]
color = 10
note = 10

[pads.12]
color = 11
note = 11

[pads.13]
color = 12
note = 12

[pads.14]
color = 13
note = 13

[pads.15]
color = 14
note = 14

[pads.16]
color = 15
note = 15
